name: wheels
on:
  push:
    branches:
      - 'wheel/**'
jobs:
  build_linux_wheels:
    name: build linux wheels
    runs-on: ubuntu-20.04
    env:
      PY_VERS: cp310-cp310 cp311-cp311 cp312-cp312
    steps:
    - uses: actions/checkout@v2
    - name: set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux_2_28_x86_64:latest /bin/bash
        docker cp . linux_build:/simplex/
    - name: run build
      run: |
        docker start linux_build
        docker exec -e PY_VERS="${PY_VERS}" linux_build /bin/bash -c "/simplex/.github/workflows/linuxbuildwheels"
        mkdir wheelhouse
        docker cp linux_build:/simplex/simplex/audited/. wheelhouse/
    - uses: actions/upload-artifact@v2
      with:
        name: linux_wheels
        path: wheelhouse/
  build_macos_wheels:
    name: build macos wheels
    strategy:
      matrix:
        os: ['macos-12', 'macos-13-xlarge']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: build wheel (3.10)
      run: .github/workflows/macosbuildwheel
    - name: set up python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: build wheel (3.11)
      run: .github/workflows/macosbuildwheel
    - name: set up python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: build wheel (3.12)
      run: .github/workflows/macosbuildwheel
    - uses: actions/upload-artifact@v2
      with:
        name: macos_wheels
        path: wheelhouse/
  build_windows_wheels:
    name: build windows wheels
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: build wheel (3.10)
      run: |
        cd simplex
        python -m pip install -U pip wheel scikit-build
        python setup.py bdist_wheel -d "${{ github.workspace }}/wheelhouse"
    - name: set up python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: build wheel (3.11)
      run: |
        cd simplex
        python -m pip install -U pip wheel scikit-build
        python setup.py bdist_wheel -d "${{ github.workspace }}/wheelhouse"
    - name: set up python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: build wheel (3.12)
      run: |
        cd simplex
        python -m pip install -U pip wheel scikit-build
        python setup.py bdist_wheel -d "${{ github.workspace }}/wheelhouse"
    - uses: actions/upload-artifact@v2
      with:
        name: windows_wheels
        path: wheelhouse/
